refactor messaging printing functions

diff --git a/run-waf b/run-waf
--- a/run-waf
+++ b/run-waf
@@ -1,29 +1,28 @@
 #!/bin/bash
-set -e
+
+set -e # exit if command returns non-zero exit code
 
 ######## FUNCTION ########
 
-# Helper function for printing formatted colorfule messages.
+# Print colorful messages to STDOUT.
 print_msg() {
     msg=$1
-    # https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
-    COLOR='\033[0;34m'
-    NC='\033[0m' # No Color
-    printf "${COLOR}--> ${msg}${NC}\n"
-}
+    msg_type=$2
 
-print_err() {
-    msg=$1
     # https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
-    COLOR='\033[0;31m'
-    NC='\033[0m' # No Color
-    printf "${COLOR}${msg}${NC}\n"
-}
+    case $msg_type in
+        err)
+            COLOR='\033[0;31m'
+            ;;
+        ok)
+            COLOR='\033[0;32m'
+            ;;
+        *)
+            COLOR='\033[0;34m'
+            ;;
 
-print_ok() {
-    msg=$1
-    # https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
-    COLOR='\033[0;32m'
+    esac
+
     NC='\033[0m' # No Color
     printf "${COLOR}${msg}${NC}\n"
 }
@@ -104,10 +103,10 @@ test_waf_is_up() {
     sleep 3
     if curl -sI localhost:80 | grep -E "^HTTP.*OK" > /dev/null; then
         docker ps
-        print_ok "WAF is up and running"
+        print_msg "WAF container is up and running" "ok"
     else
         docker logs testing-waf
-        print_err "WAF is not working"
+        print_msg "WAF container is not working" "err"
     fi
 }
 
